// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztxizfuqyokfanotvnzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0eGl6ZnVxeW9rZmFub3R2bnp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODAyMDAsImV4cCI6MjA2OTg1NjIwMH0.WeEGxGTWQbeF_D9cS0LCMEFLo6n_M8ZcTDkjIJh7Drk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});